// AUTO-GENERATED by scripts/optimize-images.ts — do not edit by hand.
// Lists slugs for which /public/species/<slug>.webp + -thumb.webp exist.

export const SPECIES_WITH_IMAGES = new Set<string>([
  "abalone",
  "barramundi",
  "blue-swimmer-crab",
  "bream",
  "calamari",
  "coral-trout",
  "flathead",
  "king-george-whiting",
  "mahi-mahi",
  "mud-crab",
  "mulloway",
  "mussels",
  "octopus",
  "oysters",
  "pearls",
  "prawns",
  "rocklobster",
  "salmon",
  "sardines",
  "scallops",
  "snapper",
  "spanner-crab",
  "tuna",
  "western-rock-lobster"
]);

export function hasSpeciesImage(slug: string): boolean {
  return SPECIES_WITH_IMAGES.has(slug);
}

export function speciesImagePath(
  slug: string,
  variant: "hero" | "thumb" = "hero",
): string | null {
  if (!SPECIES_WITH_IMAGES.has(slug)) return null;
  return variant === "thumb"
    ? `/species/${slug}-thumb.webp`
    : `/species/${slug}.webp`;
}
