/**
 * Optimize source PNG species photos into two WebP variants:
 *   public/species/<slug>.webp         (hero, 1200w)
 *   public/species/<slug>-thumb.webp   (card, 400w)
 *
 * Source: /images/<something>.png (2.5-3MB each)
 * Target: ~100-200KB hero, ~20-40KB thumb.
 *
 * Also writes src/data/species/image-manifest.ts — a typed Set<Slug> of
 * species that have photos, so the UI can decide between <SpeciesImage>
 * and the emoji fallback.
 *
 * Idempotent: skips output files that are newer than their source.
 *
 * Run:  npm run images
 */
import { readdirSync, statSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, parse } from "node:path";
import sharp from "sharp";

const SRC_DIR = join(process.cwd(), "images");
const OUT_DIR = join(process.cwd(), "public", "species");
const MANIFEST = join(process.cwd(), "src", "data", "species", "image-manifest.ts");

/**
 * Filename-without-extension -> species slug in records.ts.
 * Filenames in /images don't always match slugs (plural/singular, typos).
 */
const slugMap: Record<string, string> = {
  abalone: "abalone",
  barramundi: "barramundi",
  BlueSwimmerCrab: "blue-swimmer-crab",
  calamari: "calamari",
  coraltrout: "coral-trout",
  flathead: "flathead",
  kinggeorgewhiting: "king-george-whiting",
  kingprawn: "prawns",
  mahimahi: "mahi-mahi",
  mudcrab: "mud-crab",
  mulloway: "mulloway",
  mussles: "mussels", // source filename has typo
  octopus: "octopus",
  oyster: "oysters",
  pearls: "pearls",
  salmon: "salmon",
  sardines: "sardines",
  scallop: "scallops",
  snapper: "snapper",
  southernrocklobster: "rocklobster",
  spannecrab: "spanner-crab", // source filename has typo
  westernrocklobster: "western-rock-lobster",
  yellowfinbream: "bream",
  yellowfintuna: "tuna",
};

mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SRC_DIR).filter((f) => /\.png$/i.test(f));

const processed: Array<{ slug: string; heroKB: number; thumbKB: number }> = [];
const skipped: string[] = [];

async function processOne(file: string) {
  const base = parse(file).name;
  const slug = slugMap[base];
  if (!slug) {
    skipped.push(`${file} (no slug mapping)`);
    return;
  }

  const src = join(SRC_DIR, file);
  const srcMtime = statSync(src).mtimeMs;

  const heroOut = join(OUT_DIR, `${slug}.webp`);
  const thumbOut = join(OUT_DIR, `${slug}-thumb.webp`);

  const heroFresh = existsSync(heroOut) && statSync(heroOut).mtimeMs > srcMtime;
  const thumbFresh = existsSync(thumbOut) && statSync(thumbOut).mtimeMs > srcMtime;

  if (!heroFresh) {
    await sharp(src)
      .resize({ width: 1200, withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 })
      .toFile(heroOut);
  }
  if (!thumbFresh) {
    await sharp(src)
      .resize({ width: 400, withoutEnlargement: true })
      .webp({ quality: 80, effort: 5 })
      .toFile(thumbOut);
  }

  const heroKB = Math.round(statSync(heroOut).size / 1024);
  const thumbKB = Math.round(statSync(thumbOut).size / 1024);
  processed.push({ slug, heroKB, thumbKB });
}

async function main() {
  for (const f of files) {
    await processOne(f);
  }

  // Emit the manifest so the runtime knows which slugs have images.
  const slugsWithImages = processed.map((p) => p.slug).sort();
  const manifestTs = `// AUTO-GENERATED by scripts/optimize-images.ts — do not edit by hand.
// Lists slugs for which /public/species/<slug>.webp + -thumb.webp exist.

export const SPECIES_WITH_IMAGES = new Set<string>(${JSON.stringify(
    slugsWithImages,
    null,
    2,
  )});

export function hasSpeciesImage(slug: string): boolean {
  return SPECIES_WITH_IMAGES.has(slug);
}

export function speciesImagePath(
  slug: string,
  variant: "hero" | "thumb" = "hero",
): string | null {
  if (!SPECIES_WITH_IMAGES.has(slug)) return null;
  return variant === "thumb"
    ? \`/species/\${slug}-thumb.webp\`
    : \`/species/\${slug}.webp\`;
}
`;
  writeFileSync(MANIFEST, manifestTs);

  const totalKB = processed.reduce(
    (sum, p) => sum + p.heroKB + p.thumbKB,
    0,
  );
  console.log(`✓ Processed ${processed.length} species images`);
  console.table(processed);
  console.log(`  Total output: ${(totalKB / 1024).toFixed(2)} MB`);
  console.log(`  Manifest: ${MANIFEST}`);
  if (skipped.length) {
    console.warn(`\n⚠ Skipped ${skipped.length} files:`);
    skipped.forEach((s) => console.warn(`  - ${s}`));
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
